### ISSUE TITLE
IllegalStateException when trying use setAudioStreamType(AudioManager.STREAM_VOICE_CALL);

### ISSUE THREAD

**Issue by dajver** [wseemann/FFmpegMediaPlayer#131]
What to do?

mp.setAudioStreamType(AudioManager.STREAM_VOICE_CALL);

always crash app with IllegalStateException

FATAL EXCEPTION: main
                                                                        Process: com.project.postercast, PID: 15151
                                                                        java.lang.IllegalStateException
                                                                            at wseemann.media.FFmpegMediaPlayer.getCurrentPosition(Native Method)
                                                                            at com.project.postercast.ui.main.listen.posters.sections.poster.section.BrowsingListeningTabFragment.run(BrowsingListeningTabFragment.java:278)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by wseemann** [comment]
Fixed in latest release.
