### ISSUE TITLE
Cannot play music on Android 6.0

### ISSUE THREAD

**Issue by osugo** [wseemann/FFmpegMediaPlayer#77]
I have included the library and it works fine for all other platforms but on a Nexus 6 running Marshmallow,  I get the following error :

```
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.radioafrica.music-1/lib/arm/libavcodec.so: has text relocations
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at wseemann.media.FFmpegMediaPlayer.<clinit>(FFmpegMediaPlayer.java:620)
at com.radioafrica.music.service.MusicService.createFFmpegMediaPlayerIfNeeded(MusicService.java:369)
at com.radioafrica.music.service.MusicService.startRadio(MusicService.java:904)
at com.radioafrica.music.service.MusicService.processRadioRequest(MusicService.java:512)
at com.radioafrica.music.service.MusicService.onStartCommand(MusicService.java:432)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
at android.app.ActivityThread.-wrap17(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Is there a workaround or a fix for this?

**Comment by pfaffenrodt** [comment]
#64

**Comment by vanwafang** [comment]
Hello @osugo please take a look at my post in another issue thread 
https://github.com/wseemann/FFmpegMediaPlayer/issues/64#issuecomment-200596869
