### ISSUE TITLE
Linked Error on Android 4.3 -  111 cannot locate 'srand'

### ISSUE THREAD

**Issue by cooltechworks** [wseemann/FFmpegMediaPlayer#89]
Linked Error on Android 4.0.4 & 4.3
------------------------------------------------
I downloaded the [Prebuilt AARs] (https://github.com/wseemann/FFmpegMediaPlayer/releases/download/v1.0.1/prebuilt-aars.zip) and added as gradle dependency. When I used the library, the app works fine on Android Marshmallow while on lower versions, the app is crashing. It is also reproducible in your [demo app] (https://github.com/wseemann/FFmpegMediaPlayer/blob/master/FMPDemo.apk?raw=true)

Steps:
-----------

1. Download the Demo app - [FMPDemo.apk] (https://github.com/wseemann/FFmpegMediaPlayer/blob/master/FMPDemo.apk?raw=true)
2. Install on device on Android Icecream sandwich (4.0.4) or Jellybean (4.3)
3. Launch the app.
4. Tap on 'Audio Demo' button.
5. Wait for the app to crash

Stacktrace:
---------------

```
E/AndroidRuntime(15300): FATAL EXCEPTION: main
E/AndroidRuntime(15300): java.lang.ExceptionInInitializerError
E/AndroidRuntime(15300): 	at wseemann.media.fmpdemo.service.MediaPlaybackService$MultiPlayer.<init>(MediaPlaybackService.java:1901)
E/AndroidRuntime(15300): 	at wseemann.media.fmpdemo.service.MediaPlaybackService.onCreate(MediaPlaybackService.java:327)
E/AndroidRuntime(15300): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2267)
E/AndroidRuntime(15300): 	at android.app.ActivityThread.access$1600(ActivityThread.java:128)
E/AndroidRuntime(15300): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1215)
E/AndroidRuntime(15300): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(15300): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(15300): 	at android.app.ActivityThread.main(ActivityThread.java:4517)
E/AndroidRuntime(15300): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(15300): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(15300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
E/AndroidRuntime(15300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
E/AndroidRuntime(15300): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(15300): Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1286]:   111 cannot locate 'srand'...
E/AndroidRuntime(15300): 
E/AndroidRuntime(15300): 	at java.lang.Runtime.loadLibrary(Runtime.java:370)
E/AndroidRuntime(15300): 	at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime(15300): 	at wseemann.media.FFmpegMediaPlayer.<clinit>(FFmpegMediaPlayer.java:616)
E/AndroidRuntime(15300): 	... 13 more

````

**Comment by MrVilkaman** [comment]
+1

**Comment by wseemann** [comment]
This is fixed in the [latest release](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.2).
